# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --prefer-offline && yarn cache clean

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_NODE_ENV
ARG NEXT_PUBLIC_AUTH_API_URL
ARG NEXT_PUBLIC_API_ENDPOINT_URL
ARG NEXT_PUBLIC_API_MEDIA_URL
ARG NEXT_PUBLIC_GOOGLE_LOGIN_CALLBACK_URL
ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_TINYMCE_URL
ARG NEXT_PUBLIC_APP_USERNAME
ARG NEXT_PUBLIC_APP_PASSWORD
ARG NEXT_PUBLIC_GRANT_TYPE_REFRESH_TOKEN
ARG NEXT_PUBLIC_MEDIA_HOST
ARG NEXT_PUBLIC_ACCESS_KEY
ARG NEXT_PUBLIC_CLIENT_TYPE

ENV NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV
ENV NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL
ENV NEXT_PUBLIC_API_ENDPOINT_URL=$NEXT_PUBLIC_API_ENDPOINT_URL
ENV NEXT_PUBLIC_API_MEDIA_URL=$NEXT_PUBLIC_API_MEDIA_URL
ENV NEXT_PUBLIC_GOOGLE_LOGIN_CALLBACK_URL=$NEXT_PUBLIC_GOOGLE_LOGIN_CALLBACK_URL
ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_TINYMCE_URL=$NEXT_PUBLIC_TINYMCE_URL
ENV NEXT_PUBLIC_APP_USERNAME=$NEXT_PUBLIC_APP_USERNAME
ENV NEXT_PUBLIC_APP_PASSWORD=$NEXT_PUBLIC_APP_PASSWORD
ENV NEXT_PUBLIC_GRANT_TYPE_REFRESH_TOKEN=$NEXT_PUBLIC_GRANT_TYPE_REFRESH_TOKEN
ENV NEXT_PUBLIC_MEDIA_HOST=$NEXT_PUBLIC_MEDIA_HOST
ENV NEXT_PUBLIC_ACCESS_KEY=$NEXT_PUBLIC_ACCESS_KEY
ENV NEXT_PUBLIC_CLIENT_TYPE=$NEXT_PUBLIC_CLIENT_TYPE

RUN yarn config set ignore-scripts true && yarn build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]