export const mqttCMDs = {
  COMMENT_UNLOCKED: 'CMD_COMMENT_UNLOCKED',
  NEW_MOVIE_ITEM: 'CMD_NEW_MOVIE_ITEM',
  NEW_MOVIE: 'CMD_NEW_MOVIE',
  REPLY_COMMENT: 'CMD_REPLY_COMMENT',
  REVIEW_UNLOCKED: 'CMD_REVIEW_UNLOCKED',
  SEND_NOTIFICATION: 'CMD_SEND_NOTIFICATION',
  TOXIC_COMMENT_LOCKED: 'CMD_TOXIC_COMMENT_LOCKED',
  TOXIC_REVIEW_LOCKED: 'CMD_TOXIC_REVIEW_LOCKED',
  VOTE_COMMENT: 'CMD_VOTE_COMMENT',
  VOTE_REVIEW: 'CMD_VOTE_REVIEW'
};

export const mqttTopics = {
  MOVIE: 'notification/movie',
  ACCOUNT: 'notification/:accountId'
};
