const notificationCMDs = {
  COMMENT_UNLOCKED: 'CMD_COMMENT_UNLOCKED',
  NEW_MOVIE_ITEM: 'CMD_NEW_MOVIE_ITEM',
  NEW_MOVIE: 'CMD_NEW_MOVIE',
  REPLY_COMMENT: 'CMD_REPLY_COMMENT',
  REVIEW_UNLOCKED: 'CMD_REVIEW_UNLOCKED',
  ROOM_INVITE: 'CMD_ROOM_INVITE',
  SEND_NOTIFICATION: 'CMD_SEND_NOTIFICATION',
  TOXIC_COMMENT_LOCKED: 'CMD_TOXIC_COMMENT_LOCKED',
  TOXIC_REVIEW_LOCKED: 'CMD_TOXIC_REVIEW_LOCKED',
  VOTE_COMMENT: 'CMD_VOTE_COMMENT',
  VOTE_REVIEW: 'CMD_VOTE_REVIEW'
};

const roomCMDs = {
  CLIENT_PING: 'CMD_CLIENT_PING',
  CREATE_CHAT: 'CMD_CREATE_CHAT',
  END_ROOM: 'CMD_END_ROOM',
  KICK_PARTICIPANT: 'CMD_KICK',
  PARTICIPANT_JOIN: 'CMD_PARTICIPANT_JOIN',
  PARTICIPANT_LEFT: 'CMD_PARTICIPANT_LEFT',
  ROOM_ALL_STATE: 'CMD_ROOM_ALL_STATE',
  ROOM_PAUSE: 'CMD_ROOM_PAUSE',
  ROOM_PLAY_SPEED: 'CMD_ROOM_PLAY_SPEED',
  ROOM_PLAY: 'CMD_ROOM_PLAY',
  ROOM_SEEK: 'CMD_ROOM_SEEK',
  ROOM_STATE: 'CMD_ROOM_STATE',
  ROOM_SYNC: 'CMD_ROOM_SYNC',
  UPDATE_PARTICIPANT_COUNT: 'CMD_UPDATE_PARTICIPANT_COUNT'
};

export const mqttCMDs = {
  ...notificationCMDs,
  ...roomCMDs
};

export const mqttTopics = {
  ACCOUNT: 'notification/:accountId',
  MOVIE: 'notification/movie',
  ROOM_USER: 'room/:roomId/:userId',
  ROOM: 'room/:roomId'
};
