export const storageKeys = {
  ACCESS_TOKEN: 'access_token',
  CSRF_TOKEN: 'csrf_token',
  DISCLAIMER_SHOWN: 'disclaimer_shown',
  EMAIL: 'email',
  LAST_RESEND_TIME: 'last_resend_time',
  NOTIFICATION_TAB: 'notification_tab',
  PREVIOUS_PATH: 'previous_path',
  REFRESH_TOKEN: 'refresh_token',
  RESEND_OTP_TIME: 'resend_otp_time',
  ROOM_CURRENT_SEASON_ID: 'room_current_season_id',
  ROOM_MOVIE_ITEM_ID: 'room_movie_item_id',
  USER_KIND: 'user_kind',
  WATCH_AUTO_NEXT_EPISODE: 'watch_auto_next_episode',
  WATCH_BRIGHTNESS: 'watch_brightness',
  WATCH_RESOLUTION: 'watch_resolution',
  WATCH_SKIP_INTRO: 'watch_skip_intro',
  WATCH_SUBTITLE_BACKGROUND_COLOR: 'watch_subtitle_background_color',
  WATCH_SUBTITLE_ENABLED: 'watch_subtitle_enabled',
  WATCH_SUBTITLE_FONT_SIZE: 'watch_subtitle_font_size',
  WATCH_SUBTITLE_TEXT_COLOR: 'watch_subtitle_text_color',
  X_CLIENT_TYPE: 'X-Client-Type',
  X_CSRF_TOKEN: 'X-CSRF-Token',
  X_URL: 'X_Url'
} as const;
