export const ErrorCode = {
  // === User error code ===
  USER_ERROR_NOT_FOUND: 'ERROR-USER-ERROR-0000',
  USER_ERROR_USERNAME_EXISTED: 'ERROR-USER-ERROR-0002',
  USER_ERROR_PHONE_EXISTED: 'ERROR-USER-ERROR-0003',
  USER_ERROR_EMAIL_EXISTED: 'ERROR-USER-ERROR-0004',
  USER_ERROR_WRONG_PASSWORD: 'ERROR-USER-ERROR-0005',
  USER_ERROR_NEW_PASSWORD_SAME_OLD_PASSWORD: 'ERROR-USER-ERROR-0006',
  USER_ERROR_OTP_INVALID: 'ERROR-USER-ERROR-0007',
  USER_ERROR_RESEND_OTP_LIMIT: 'ERROR-USER-ERROR-0008',
  USER_ERROR_CONFIRM_PASSWORD_INVALID: 'ERROR-USER-ERROR-0009',

  // === User report error code ===
  USER_REPORT_ERROR_EXISTED: 'ERROR-USER-REPORT-0001',

  // === Room error code ===
  ROOM_ERROR_NOT_FOUND: 'ERROR-ROOM-0000',
  ROOM_ERROR_INVALID_TIME: 'ERROR-ROOM-0001',
  ROOM_ERROR_CODE_EXISTED: 'ERROR-ROOM-0002',
  ROOM_ERROR_INVALID_STATE: 'ERROR-ROOM-0003',
  ROOM_ERROR_INVALID_ROOM: 'ERROR-ROOM-0004',
  ROOM_ERROR_UNAUTHORIZED: 'ERROR-ROOM-0005',

  // === Participant error code ===
  PARTICIPANT_ERROR_NOT_FOUND: 'ERROR-PARTICIPANT-0000',
  ROOM_ERROR_ALREADY_JOINED: 'ERROR-PARTICIPANT-0001',
  ROOM_ERROR_HOST_NOT_JOINED: 'ERROR-PARTICIPANT-0002',

  // === Collection error code ===
  COLLECTION_ERROR_NOT_FOUND: 'ERROR-COLLECTION-0000',

  // === Movie error code ===
  MOVIE_ERROR_NOT_FOUND: 'ERROR-MOVIE-ERROR-0000',

  // === Movie item error code ===
  MOVIE_ITEM_ERROR_NOT_FOUND: 'ERROR-MOVIE-ITEM-ERROR-0000',

  // === Person error code ===
  PERSON_ERROR_NOT_FOUND: 'ERROR-PERSON-ERROR-0000',

  // === Movie person error code ===
  MOVIE_PERSON_ERROR_NOT_FOUND: 'ERROR-MOVIE-PERSON-ERROR-0000',

  // === Favorite error code ===
  FAVOURITE_ERROR_NOT_FOUND: 'ERROR-FAVOURITE-ERROR-0000',

  // === Playlist error code ===
  PLAYLIST_ERROR_NOT_FOUND: 'ERROR-PLAYLIST-ERROR-0000',

  // === Category error code ===
  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-ERROR-0000'
} as const;
