export const ErrorCode = {
  // === User error code ===
  USER_ERROR_NOT_FOUND: 'ERROR-USER-ERROR-0000',
  USER_ERROR_USERNAME_EXISTED: 'ERROR-USER-ERROR-0002',
  USER_ERROR_PHONE_EXISTED: 'ERROR-USER-ERROR-0003',
  USER_ERROR_EMAIL_EXISTED: 'ERROR-USER-ERROR-0004',
  USER_ERROR_WRONG_PASSWORD: 'ERROR-USER-ERROR-0005',
  USER_ERROR_NEW_PASSWORD_SAME_OLD_PASSWORD: 'ERROR-USER-ERROR-0006',
  USER_ERROR_OTP_INVALID: 'ERROR-USER-ERROR-0007',
  USER_ERROR_RESEND_OTP_LIMIT: 'ERROR-USER-ERROR-0008',
  USER_ERROR_CONFIRM_PASSWORD_INVALID: 'ERROR-USER-ERROR-0009',

  // === User report error code ===
  USER_REPORT_ERROR_EXISTED: 'ERROR-USER-REPORT-0001'
} as const;
